from __future__ import annotations
import pandas as pd
from btfi.__version__ import __version__
from datetime import datetime

def generate_markdown(experiment_id: int, title: str, config: dict, metrics: dict, annual_df: pd.DataFrame, verdict: str, verdict_reason: str, warnings: list[str], rolling: dict, btfi_score_components: dict) -> str:
    w_str = "\n".join([f"> ⚠️ {w}" for w in warnings]) if warnings else "> No major data warnings."
    annual_table = ""
    if annual_df is not None and not annual_df.empty:
        annual_table = "| Year | Strategy | S&P 500 | Excess |\n|------|---------:|--------:|-------:|\n"
        for _, r in annual_df.iterrows():
            annual_table += f"| {int(r['year'])} | {r['strategy']*100:.1f}% | {r['benchmark']*100:.1f}% | {r['excess']*100:.1f}% |\n"
    else:
        annual_table = "_Insufficient data for annual returns._\n"

    limitations = ""
    if any("look-ahead" in w.lower() for w in warnings):
        limitations += "- ⚠️ **Look-ahead bias risk:** Fundamental publication dates unavailable via yfinance. Results may be optimistic.\n"
    if any("survivorship" in w.lower() for w in warnings):
        limitations += "- ⚠️ **Survivorship bias:** Using current S&P 500 constituents, not historical. Upward bias likely.\n"
    if not limitations:
        limitations = "- No known major limitations beyond standard yfinance constraints.\n"

    md = f"""# BTFI #{experiment_id:03d}: {title}

> **Thesis:** Does *{config.get('name','Strategy')}* beat simply owning the S&P 500?

**Strategy Rules:**
- Universe: {config.get('universe','sp500')} {'(current constituents)' if config.get('universe')=='sp500' else ''}
- Ranking: {config.get('metric','momentum_12m')} {f"formula: `{config.get('formula')}`" if config.get('formula') else ""}
- Selection: Top {config.get('top_n','20')}
- Weighting: {config.get('weighting','equal')}
- Rebalance: {config.get('rebalance','annual')}
- Costs: {config.get('transaction_cost_bps',10)} bps + {config.get('slippage_bps',5)} bps slippage
- Benchmark: S&P 500 proxy: {config.get('benchmark','SPY')}
- Period: {config.get('start_date','')} to {config.get('end_date','')}

**Warnings & Data Quality:**
{w_str}

## Key Performance

| Metric | Strategy | S&P 500 |
|--------|---------:|--------:|
| CAGR | {metrics.get('cagr',0)*100:.2f}% | {metrics.get('benchmark_cagr',0)*100:.2f}% |
| Excess CAGR | {metrics.get('excess_cagr',0)*100:.2f}% | — |
| Volatility | {metrics.get('volatility',0)*100:.1f}% | {metrics.get('benchmark_volatility',0)*100:.1f}% |
| Sharpe | {metrics.get('sharpe',0):.2f} | — |
| Max Drawdown | {metrics.get('max_drawdown',0)*100:.1f}% | {metrics.get('benchmark_max_drawdown',0)*100:.1f}% |
| Calmar | {metrics.get('calmar',0):.2f} | — |
| Beta | {metrics.get('beta',0):.2f} | 1.00 |
| Alpha | {metrics.get('alpha',0)*100:.2f}% | — |

## Annual Returns

{annual_table}

## Rolling Analysis

- 5Y Win Rate: {rolling.get('beat_pct',0) if rolling else 0}% of {rolling.get('total_periods',0) if rolling else 0} periods
- Median Excess: {rolling.get('median_excess',0)*100 if rolling and 'median_excess' in rolling else 0:.2f}%

## BTFI Score: {btfi_score_components.get('btfi_score',0)}/100

| Component | Score |
|-----------|------:|
| Excess CAGR ({btfi_score_components.get('excess_cagr',0)}%) | {btfi_score_components.get('excess_score',0)} |
| Sharpe ({btfi_score_components.get('sharpe',0)}) | {btfi_score_components.get('sharpe_score',0)} |
| Drawdown ({btfi_score_components.get('max_drawdown',0)}%) | {btfi_score_components.get('drawdown_score',0)} |
| Win Rate ({btfi_score_components.get('win_rate_5y',0)}%) | {btfi_score_components.get('win_rate_score',0)} |
| Param Robustness ({btfi_score_components.get('param_win_rate',0)}%) | {btfi_score_components.get('param_score',0)} |
| Cost Robustness | {btfi_score_components.get('cost_score',0)} |

## Verdict: **{verdict}**

> {verdict_reason}

## Methodology & Limitations

{limitations}
- Execution: Signal at t → execute at t+1 close (look-ahead prevented for prices).
- Fundamentals: Effective dates approximated; publication lag not modeled — flagged above.
- Corporate actions: Splits/dividends via yfinance adjusted closes; special dividends where available.
- Reproducibility: Config hash {config} — rerunnable with identical cached data.
- Software: BTFI v{__version__} ({datetime.utcnow().date()})

## Charts

_Growth of $10,000, drawdown, rolling returns, concentration charts available in the app. Export PNG/SVG from the Experiment page._

---
*Generated by BTFI — Buy the Fucking Index. The burden of proof is on the strategy, not the index.*
"""
    return md

def generate_json_export(config: dict, metrics: dict, verdict: str, score: dict) -> dict:
    return {"config": config, "metrics": metrics, "verdict": verdict, "btfi_score": score}
